In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# ✨ Outline of Today's Notebook: 

1. Tensor aggregation
2. The position of the aggregations
3. Reshaping, stacking, squeezing, and unsqueezing
4. Selecting data from tensors (indexing)
5. PyTorch and NumPy

YT covered till: `3:42:09`

## 🔵 Finding the min, max, mean, sum (tensor aggregation)
- Finding the min: `torch.min(tensorName)/x.min()`
- Finding the max: `torch.max(tensorName)/x.max()`
- Finding the sum: `torch.sum(tensorName)/x.sum()`
- Finding the mean: we need to have tensor of type float32
  `torch.mean(x.type(torch.float32))`

In [9]:
# Create a tensor
x = torch.arange(1, 100, 10)
print(x)

# Finding the min: 
print(f"The min value is: {torch.min(x)}")
print(f"The max value is: {x.max()}")
print(f"The sum value is: {torch.sum(x)}")
print(f"The mean value is: {torch.mean(x.type(torch.float32))}")

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])
The min value is: 1
The max value is: 91
The sum value is: 460
The mean value is: 46.0


## 🔵 Finding the position of min, max, ...
- Finding the position of min: `tensorName.argmin()`
- Finding the position of max: `tensorName.argmax()`

In [11]:
print(x)
print(f"The index/position of min value is: {x.argmin()}")
print(f"The index/position of max value is: {x.argmax()}")

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])
The index/position of min value is: 0
The index/position of max value is: 9


## 🔵 Reshaping, stacking, squeezing, and unsqueezing

**Useful in helping us debugging the shape and dimensions essiues**

- **Reshaping**: reshapes an input tensor to a defined shape
- **View**: Return a view of an input tensor of certain shape but keep the same memory as the original tensor
- **Stacking**: Compbine multiply tenosr on top of each other (vstack) or side by side (hstack)
- **Squeeze**: Remove all `1` dimensions from a tensor
- **Unsqueeze**: add all `1` dimensions to a target tensor
- **Permute**: Return a view of the input with dimensions permuted (swapped) in a certain way


#### 🟢 Reshaping and View:

In [14]:
# Let's create a tensor first
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [19]:
# Add an extera dimensions
x_reshaped = x.reshape(3, 3)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [22]:
# Change the view: A view return a view of input tensor, but their memories are same
z = x.view(1,9)
z, z.shape

# change in z = change in x
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

#### 🟢 Stack and Squeeze:

In [28]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked
# The dim should be compatible to the actual tensor x. 
# similar thing for adding a dimension

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [40]:
x_reshaped = x.reshape(1, 9)
# Squeeze and Unsqueeze
# torch.squeeze - removes all single dimensions from target tensor

print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Now we romve the extera dimension from x_reshaped:
x_reshaped_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_reshaped_squeezed}")
print(f"New shape: {x_reshaped_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [53]:
# Another example
y = torch.tensor([[[1, 2, 3]]])
y_reshaped = y.reshape(1, 3, 1)

print(f"Previous tensor: {y_reshaped}")
print(f"Previous shape: {y_reshaped.shape}")

# Now we romve the extera dimensions from y_reshaped:
y_reshaped_squeezed = y_reshaped.squeeze()
print(f"\nNew tensor: {y_reshaped_squeezed}")
print(f"New shape: {y_reshaped_squeezed.shape}")

Previous tensor: tensor([[[1],
         [2],
         [3]]])
Previous shape: torch.Size([1, 3, 1])

New tensor: tensor([1, 2, 3])
New shape: torch.Size([3])


#### 🟢 Unsqueeze:

In [57]:
# torch unsqueeze - adds a single dimension ro a target tensor at a specific dim
print(f"Previous squeezed shape: {y_reshaped_squeezed}")
print(f"Previous squeezed shape: {y_reshaped_squeezed.shape}")

# Add an extera dimension with unsqueeze:
y_unsqueezed = y_reshaped_squeezed.unsqueeze(dim=1)
print(f"\nNew tensor: {y_unsqueezed}")
print(f"New shape: {y_unsqueezed.shape}")


Previous squeezed shape: tensor([1, 2, 3])
Previous squeezed shape: torch.Size([3])

New tensor: tensor([[1],
        [2],
        [3]])
New shape: torch.Size([3, 1])


#### 🟢 Permute:

In [59]:
# Permute basically changes the dimensions. 
# In ML dimensions represent a sort of information of our data
# Like in photos we have height width, and RGB
# Now let's say we have a picture that is beinge represented by a tensor of numbers
# and its shape is like size=(224, 224, 3) (height, width, RGB)
# Now we want to have the shape of (3, 224, 224) (RGB, height, width)
# So the RGB is at the beginning

# we map using permute:
# map perv index -> new index
# map index(2) -> index(0) so RGB at dim=0
# map index(0) -> index(1) so height at dim=1
# map index(1) -> index(2) so width at dim=2

# Permute(index(2), index(0), index(1)) so index 2 at the index 0 of permute
# index(0) at the index(1) of permute and continuing to fill the arguments...

x_original = torch.rand(size=(224, 224, 3)) # [height, width, colour_channel]

# permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1)

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


🟣 **Challenge:** Change a value of x_original, and see if it changes in x_permuted. If so, explain why?

In [60]:
print(f"Previous value at index 0, 0, 0 of x_original: {x_original[0, 0, 0]}")
x_original[0, 0, 0] = 10

print(f"New value at index 0, 0, 0 of x_original: {x_original[0, 0, 0]}")
# Now we check the x_permuted:
print(f"New value at index 0, 0, 0 of x_permuted: {x_permuted[0, 0, 0]}")

Previous value at index 0, 0, 0 of x_original: 0.5569123029708862
New value at index 0, 0, 0 of x_original: 10.0
New value at index 0, 0, 0 of x_permuted: 10.0


_Answer: The reason is that x_permuted is a view of x_original, and a view has the same memory address of x_original. So any changes in x_original will result a change in x_permuted as well._

## 🔵 Selecting Data from Tensors (Indexing)

Indexing in PyTorch is similar to indexing with Numpy. 

In [74]:
# Create a Tensor:
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [71]:
# Let's index on our new tensor: 
x[0]

tensor(6)

In [72]:
x[0][0]

tensor([1, 2, 3])

In [73]:
x[0][0][0]

tensor(1)

In [75]:
x[0, 2, 2]

tensor(9)

In [81]:
x[:, :, 1]

tensor([[2, 5, 8]])

In [82]:
# Get all values of 0th and 1st dimensions but only index 1 of second dimension
x[:, :, 1]
# The indexing is related to the dimesnions. 
# So when we have : in dim=0, it goes through all elements in the most outer []
# Similarly : in dim=1 goes through all the rows we have. 
# but 1 in dim=2 means that we only want the value at index 1 of dim2, so in each row
# we take the second col/index

tensor([[2, 5, 8]])

In [83]:
# Get all values of the 0 dimension but only the 1 index of 1 and second dimension:
x[:, 1, 1]

tensor([5])

In [86]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension: (first row)
print(x[0, 0, :])
# get index 0 of 0th and 2nd dimension and all values of first dimension: (first col)
print(x[0, :, 0])

tensor([1, 2, 3])
tensor([1, 4, 7])


**🟣 Challenge:** Get the last column of the tensor:


In [87]:
print(x[0, :, 2])

tensor([3, 6, 9])


## 🔵 PyTorch and NumPy

NumPy is a popular scientific Python numerical computing library. 
And because of this, PyTorch has functionality to interact with it. 

* NumPy --> PyTorch tensor: `torch.from_numpy(ndarray)`
* PyTorch tensor --> NumPy: `torch.Tensor.numpy()`

In [89]:
# NumPy array to Tensor:

array = np.arange(1.0, 8.0)
# Warning: when converting from numpy -> pytorch, pytorch reflects numpy a 
# default of dtype = float64

# Tensor will get a new memory:
tensor = torch.from_numpy(array) 
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [91]:
# Change the value of the array?
array_changed = array + 1
array_changed, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [92]:
# Tensor to numpy array: 
tensor_example = torch.ones(7)
numpy_tensor = tensor_example.numpy()
tensor_example, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [94]:
tensor_changed = tensor_example + 1
tensor_changed, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))