In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# ✨ Outline of Today's Notebook: 

1. PyTorch Reproducibility
2. Different Ways of Accessing a GPU in PyTorch
3. Setting up device agnostic code

YT covered till: `3:42:09`

## 🔵 PyTorch Reproducipility (trying to take the random out of random)

In short how a neural network learns:

`start with random numbers -> perform tensor operations -> update random numbers to try and make better representation of data -> again -> again -> again...`

To reduce the randomness in neural networks and pytorch comes the concept of **random seed**. 

It is a way to get the same random variables as another notebook and every time we run it doesn't change the randomness. 

**How to do it?**

    1. Set a RANDOM_SEED to a constant number
    2. Call torch.manual_seed(RANDOM_SEED) before making a random tensor. 

In [4]:
# Create two random tensor
tensor_A = torch.rand(3, 4)
tensor_B = torch.rand(3, 4)

print(tensor_A)
print(tensor_B)
print(tensor_A == tensor_B)

tensor([[0.6560, 0.4304, 0.2106, 0.6585],
        [0.4063, 0.4156, 0.5464, 0.8180],
        [0.5397, 0.3879, 0.2934, 0.0737]])
tensor([[0.8581, 0.3382, 0.3497, 0.3363],
        [0.7743, 0.3615, 0.1203, 0.3496],
        [0.9867, 0.5600, 0.5715, 0.8553]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [7]:
# Let's make but reproducible tensors:

# Set the random seed
RANDOM_SEED = 6 # It can be anything

torch.manual_seed(RANDOM_SEED)
tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
tensor_D = torch.rand(3, 4)

print(tensor_C)
print(tensor_D)
print(tensor_C == tensor_D)

tensor([[0.5722, 0.5539, 0.9868, 0.6080],
        [0.2347, 0.4492, 0.6743, 0.7480],
        [0.5601, 0.1674, 0.3333, 0.4648]])
tensor([[0.5722, 0.5539, 0.9868, 0.6080],
        [0.2347, 0.4492, 0.6743, 0.7480],
        [0.5601, 0.1674, 0.3333, 0.4648]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## 🔵 Different Ways of Accessing a GPU in PyTorch

This is about running tensors and pyTorch objects on the GPUs and making faster computations. 

**GPU:** faster computation on numbers, thanks to CUDA + NVIDIA hardware + PyTorch working behind the scenes. 

#### 🟢 1. Getting a GPU:
1. Esiest - Use a Google Colab for a free GPU (options to upgrade as well) -> Small experiments
Larger Experiments:
3. Use your own GPU - takes a it of set up and requires investment of purchasing a GPU...
4. Use cloud computing - GCP, AWS, Azura, these services allows you to rent computers on the cloud ad access them.
 
For 2, 3 PyTorch + GPU derivers(CUDA) takes a little bit of setting up, to do this, refer to **PyTorch set up documentation**. 

In [9]:
!nvidia-smi # CHECK WHY IT IS NOT WORKING

zsh:1: command not found: nvidia-smi


#### 🟢 2. Check for GPU access for the PyTorch

In [12]:
# This will get an error because cuda and nvidia is not on my local work space
# WORK ON IT:
# torch.cude.is_available() should give us true. 

In [13]:
# Setup device agnostic code:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [14]:
# Count the number of GPUs 
torch.cuda.device_count()

0

## 🔵 Setting up device agnostic code

How can we actually use the GPU? Putting tensors and models on the GPU is because GPU results in a fatser computations. 

This way we can find patterns faster, run experiment fasters, and just having a better result in general since we run the program faster. 

**How to change the device?** Use `tensorName.to(device)` where device is cpu, cuda, ...

In [15]:
# Create a tensor (defalt on CPU)
tensor = torch.tensor([1, 2, 3], device="cpu")

# Tensor is not on GPU:
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


#### 🟢 Changing to Other Devices:

In [19]:
# Move tensor to GPU (if available)
tensor_on_GPU = tensor.to(device)
tensor_on_GPU.device

# But since we don't have cuda available we still have it in cpu, 
# so we have bto down;oad the gpu on here. 

device(type='cpu')

#### 🟢 Moving tensors back to CPU

If tensor is on GPU, we can't transorm it to numpy. SO we have to bring it back to CPU. 

**How to change the devce from GPU -> CPU?** Use `tensosrName.cpu()`