In [24]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.8.0


## Introduction to tensors
### Creating tensors

pytorch tensors are created using `torch.tensor`. Read the documentation in pytorch web. 

In [25]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [26]:
scalar.ndim

0

In [27]:
# Get the tensor back into python int: 
scalar.item()

7

### Vectors:

In [28]:
# Vector: has magnitude and dirction
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [29]:
vector.ndim

1

In [30]:
vector.shape

torch.Size([2])

### MATRIX

In [44]:
# MATRIX
MATRIX = torch.tensor([[1, 2, 5], 
                       [3, 4, 6]])
MATRIX

tensor([[1, 2, 5],
        [3, 4, 6]])

In [45]:
MATRIX.ndim

2

In [46]:
MATRIX[1]

tensor([3, 4, 6])

In [34]:
MATRIX.shape

torch.Size([2, 2])

### Tenosrs: 

In [ ]:
# TENSOR:
TENSOR = torch.tensor([[[1, 2, 3], 
                        [4, 5, 6], 
                        [7, 8, 9], 
                       [10, 11, 12]], 
                       
                       [[1, 2, 3], 
                        [4, 5, 6], 
                        [7, 8, 9], 
                       [14, 15, 16]]])
TENSOR

In [43]:
TENSOR.shape

torch.Size([2, 4, 3])

2 is the dim of the very outer matrix, 4 is the dim of how many rows we have, and 3 is the dim of how many element we have in each row, or how many cols. 

### Random Tensors

Why Random Tensors? 

Random Tensors are important because the way many neural network works is that they start with tensors full of random numbers and then adjust those numbers to better represent of data

`start with random num -> look at data -> update the random numbers -> look at data -> update random numbers`

In [52]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4, 10)
random_tensor

tensor([[[0.7712, 0.2695, 0.1731, 0.5083, 0.6863, 0.7779, 0.9670, 0.5461,
          0.0131, 0.8457],
         [0.7493, 0.0543, 0.3955, 0.3322, 0.3403, 0.5281, 0.5815, 0.9511,
          0.6656, 0.8855],
         [0.5999, 0.7177, 0.6342, 0.4414, 0.9260, 0.1113, 0.3655, 0.6179,
          0.9748, 0.5751],
         [0.8687, 0.8478, 0.9481, 0.6556, 0.8556, 0.6454, 0.3199, 0.2858,
          0.1346, 0.0618]],

        [[0.7890, 0.0647, 0.5044, 0.5425, 0.6230, 0.9934, 0.2360, 0.5009,
          0.3114, 0.0290],
         [0.5504, 0.8210, 0.6544, 0.4390, 0.7814, 0.0513, 0.8062, 0.3795,
          0.6483, 0.3633],
         [0.7123, 0.1000, 0.7314, 0.9602, 0.7556, 0.5311, 0.2161, 0.7407,
          0.2994, 0.9226],
         [0.0624, 0.8053, 0.3153, 0.0036, 0.9976, 0.2190, 0.9154, 0.8132,
          0.5142, 0.0906]],

        [[0.3026, 0.8952, 0.9801, 0.1855, 0.5436, 0.3777, 0.7431, 0.3611,
          0.3150, 0.7382],
         [0.7861, 0.7511, 0.0886, 0.8362, 0.0336, 0.3781, 0.5841, 0.2686,
          0.6

In [53]:
random_tensor.ndim

3

In [56]:
# Create a random tensor with a similar shape to an image tensor:
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and Ones

Helpful for creating a mask.
- Making some numbers to zero in your random tensor by multiplying them to zero tensor
- Saving some of the tensor info by multiplying it to ones. 

In [57]:
# Create a tensor of all zeros: 
zeros = torch.zeros(3, 4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [58]:
ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [59]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [68]:
# Use torch.arange()
one_to_nine = torch.arange(start=1, end=10, step=1)
one_to_nine

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [70]:
# Creating tensor-like use zeros_like, ones_like
nine_zeros = torch.zeros_like(one_to_nine)
nine_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0])