In [38]:
import torch
import numpy as np
import pandas as pd
from IPython import display

### ✨ Outline of Today's Notebook: 

1. Talking about tensor data types
2. Tensor attributes (dtype, shape, device)
3. Tensor Operations
4. Matrix Multiplications with Tensors
5. Common error in PyTorch and DL

YT covered till: `2:49:58`

### 🔵 Tensor Data Type

General Knowledge: **Percisions**

    Precision of a numerical quantity that says how much detail the quantity expresses. 
    The default of torch.tensor is float32, which is 32 bits. 
    The lower the precision is, the faster calculations we have. 

**Note:** Tensor datatype is one of the 3 big errors we run into with PyTorch and DL: 
1. Tensors not right datatype --> ex: doing calculations with another tensor of different datatype
2. Tensors not correct shape. 
3. Tensors not on the correct device. --> Devices of tensors when doing calculations must be the same. 

In [11]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 8.0, 9.0], 
                               dtype=None, # what datatype is the tensor (float32, float 16)
                               device=None, # what device is your tensor on, like gpu, cpu, cuba, ...
                               requires_grad=False) # whether or not to track gradients with these tensor operations. 

In [9]:
float_32_tensor.dtype

torch.float32

In [10]:
# Tackling the first problem:

float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 8., 9.], dtype=torch.float16)

In [13]:
int_32_tensor = torch.tensor([1, 3, 6], dtype=torch.int32)
float_32_tensor * int_32_tensor

tensor([ 9., 64., 81.])

### 🔵 Getting Information from tensors: (Tensor Attributes)

1. Tensors not right datatype - getting info on tensor datatype: `tensorName.dtype`
2. Tensors not correct shape. - getting info on tensor shape: `tensorName.shape`
3. Tensors not on the correct device. - getting info on tensor device: `tensorName.device`

**Example:**

In [21]:
example_tensor = torch.rand(3, 4)

print(example_tensor)
print(f"DataType of tensosr: {example_tensor.dtype}")
print(f"Shape of tensosr: {example_tensor.shape}")
print(f"Device of tensosr: {example_tensor.device}")

tensor([[8.5937e-01, 7.1861e-02, 9.8357e-01, 3.3704e-01],
        [3.5621e-01, 4.5425e-04, 6.2215e-01, 3.1231e-01],
        [3.2111e-01, 3.4486e-01, 7.2888e-01, 8.6456e-01]])
DataType of tensosr: torch.float32
Shape of tensosr: torch.Size([3, 4])
Device of tensosr: cpu



**Changing the dtype:** either making a new one or changing a tensor type to another dtype, ex: `tensorName.type(torch.int32)`



### 🔵 Manipulating Tensors (tensor operations)

Tensor Operations include: 
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix Multiplication

**Example:**

In [30]:
tensor = torch.tensor([1, 2, 3])

print(tensor + 10)
print(tensor * 10)
print(tensor - 10)
print(tensor / 10)

# There are also pytorch built-in functions for operations: 
torch.mul(tensor, 10)
torch.add(tensor, 10)

tensor([11, 12, 13])
tensor([10, 20, 30])
tensor([-9, -8, -7])
tensor([0.1000, 0.2000, 0.3000])


tensor([11, 12, 13])

### 🔵 Matrix Multiplication: 

Two main ways of performing in neural networks and DL

1. Element-wise multiplication
2. Matrix multiplication (dot product) --> row * col --> Use: `torch.matmul(tensor, tensor)`

More information on multiplying matrices: https://www.mathsisfun.com/algebra/matrix-multiplying.html


In [41]:
# Element-wise multiplication: 
tensor = torch.tensor([1, 2, 3])

print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [44]:
# Matrix Multiplication: 
torch.matmul(tensor, tensor)
'''
[1, 2, 3] * [1] = 1*1 + 2*2 + 3*3 = 14
            [2]
            [3]
'''
# Matrix mult by code: 
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

# It is way faster with torch.matmul(tensor, tensor)

tensor(14)


### 🔵 One of the most common error in DL:

There are two main rules that performing matrix multipication needs to satisfy: 
1. The **inner dimensions** must match:
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work

2. The resulting matrix has the shape of the **outer dimensions:**
* `(2, 3) @ (3, 2) -> (2, 2)`
* `(3, 10) @ (10, 2) -> (3, 2)`

**A VERY COOL WEBSITE FOR MATRIX MULTIPLICATION YAYYYYY 🎉💃🏻:** http://matrixmultiplication.xyz/

torch.matmul(torch.rand(3, 10), torch.rand(10, 1))

In [52]:
# Shape for matrix multiplication
tensor_A = torch.tensor([[1, 2], 
                         [3, 4], 
                         [5, 6]])

tensor_B = torch.tensor([[7, 10], 
                         [8, 11], 
                         [9, 12]])

# torch.mm(tensor_A, tensor_B) #torch.mm = torch.matmul
# tensor_A = (3x2)
# tensor_B = (3x2) 
# Problem!! 

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**. 
A **transpose** switches the axes or dimensions of a given tensor. 
How to do it? `tensorName.T`

In [57]:
print(tensor_B, tensor_B.shape)
print("Now we transpose")
print(tensor_B.T, tensor_B.T.shape)

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]]) torch.Size([3, 2])
Now we transpose
tensor([[ 7,  8,  9],
        [10, 11, 12]]) torch.Size([2, 3])


In [59]:
# The matrix multiplication operation works when tensor_B is transposed. 
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])
